# fly.toml app configuration file generated for dailygroceries on 2023-06-22T13:57:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dailygroceries"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
